// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA05nqyGhF01ZaQFC469H6aOxNwdvNQtIA',
    appId: '1:867298798987:android:891eddfe088abe380b938e',
    messagingSenderId: '867298798987',
    projectId: 'user-feedback-1238a',
    storageBucket: 'user-feedback-1238a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOC5ib299BbHzLRlTzZKL2oglpki5qU0M',
    appId: '1:867298798987:ios:106783f25e8886730b938e',
    messagingSenderId: '867298798987',
    projectId: 'user-feedback-1238a',
    storageBucket: 'user-feedback-1238a.firebasestorage.app',
    androidClientId: '867298798987-qrm09p6hoajf6p60svfoakk0hdg4lc2d.apps.googleusercontent.com',
    iosClientId: '867298798987-65aato3r0mucursc9lpf2jigc1knqnem.apps.googleusercontent.com',
    iosBundleId: 'com.harshit.feedbackcollector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOC5ib299BbHzLRlTzZKL2oglpki5qU0M',
    appId: '1:867298798987:ios:495790d0e1d434130b938e',
    messagingSenderId: '867298798987',
    projectId: 'user-feedback-1238a',
    storageBucket: 'user-feedback-1238a.firebasestorage.app',
    androidClientId: '867298798987-qrm09p6hoajf6p60svfoakk0hdg4lc2d.apps.googleusercontent.com',
    iosClientId: '867298798987-gd08rb3bv3v6oqjr43ojajabr3n1ogvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.feedbackCollector',
  );
}
